project:
  name: quickstart-liquibase-pro
  owner: quickstart-eng@amazon.com
  package_lambda: true
  lambda_source_path: lambda_functions/source
  lambda_zip_path: packages
  s3_regional_buckets: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
    # - ap-east-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
    # - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
    # - us-gov-east-1
  - us-gov-west-1
  template: templates/liquibase-pro.template
  parameters:
    ProjectName: 
    QSS3BucketName: '$[taskcat_autobucket]'
    LiquibaseProKey:
    VPCID:
    PrivateSubnet01:
    PrivateSubnet02:
    DatabaseUsernameTest:
    DatabasePasswordTest:
    DatabaseUsernameStage:
    DatabasePasswordStage:
    DatabaseUsernameProd:
    DatabasePasswordProd:
tests:
  default:
    template: templates/liquibase-pro.template
